#!/usr/bin/env bash
# gen.sh — 扫描目录，生成 embedded.mbt
# 用法: bash scripts/gen.sh ./frontend/dist > src/embedded.mbt
set -euo pipefail

DIST="${1:?usage: gen.sh <dist-dir>}"
PREFIX="${2:-}"

if [ ! -d "$DIST" ]; then
  echo "error: directory not found: $DIST" >&2
  exit 1
fi

echo "// Code generated by gen.sh; DO NOT EDIT."
echo "// Source: $DIST"
echo ""

echo "pub let EMBED_PATHS : Array[String] = ["

FILES=()
while IFS= read -r -d '' f; do
  # 计算相对路径
  rel="${f#$DIST}"
  FILES+=("$rel")
  echo "  \"$rel\","
done < <(find "$DIST" -type f -print0 | sort -z)

echo "]"
echo ""
echo "pub let EMBED_DATA : Array[String] = ["

for f in "${FILES[@]}"; do
  src="$DIST$f"
  # base64 编码（兼容 Linux / macOS）
  b64=$(base64 -w0 < "$src" 2>/dev/null || base64 < "$src" | tr -d '\n')
  echo "  \"$b64\","
done

echo "]"
